# <center>**Numpy Introduction**</center>
---

<br>

## **Numpy**
#### Numpy is short for Numerical Python. It is the fundamental package required for high performance scientific computing and data analysis. 

Some uses :

- `ndarray`, a fast and space-efficient multidimensional array for large data
- providing vectorized arithmetic operations and sophisticated broadcasting capabilities.
- Standard mathematical functions for fast operations on entire arrays of data without having to write loops.
- Tools for reading/writing array data to disk and working with memory-mapped files.
- Linear algebra, random generation, and Fourier transform capabilities.


## Importing package

In [5]:
import numpy as np

### The NumPy ndarray : A Multidimensional object

A numpy array is a grid of values, all of the `same type`, and is indexed by a tuple of nonnegative integers. 
Every object has 
- a shape = Shape is a tuple giving size of each dimension
- and a dtype = data type. 

Array() tries to infer a good type, if not given explicitly.

### Creating 1-D array

In [24]:
a1 = np.array([1,2,3,4,5]) ## Creating one dimensional array and stroing in a1 varible.
print(a1) ## Displaing array.
print(a1.dtype) ## Display data type of array.
print(type(a1)) ## Display type of the array.

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


### Creating 2-D array

In [10]:
a2 = np.array([[1,2,3],[4,7,9]]) ## Creating two dimensional array and stroing in a1 varible.
print(a2) ## Displaing array.
print(a2.dtype) ## Display data type of array.
print(type(a2)) ## Display type of the array.

[[1 2 3]
 [4 7 9]]
(2, 3)
int64


In [16]:
## Get the range of valus betweeen 10-20.
np.arange(10,20)
## range(10,20,2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Creating a 2-D array filled with zeroes

In [21]:
a3 = np.zeros([5,5]) ## Create an array with zeros.
## np.zeros((5,5))
print(a3) ## Display an array.
print(a3.shape) ## Display an array dimension.
print(a3.ndim) ## 2 dimensional array so ndim is 2.

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)
2


### Generating numbers between a range with a specific difference

In [19]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

### Generating **n** numbers between a range

In [16]:
np.linspace(0,10,5) ## In bound,out bound will be inncluded and we are specifying number eleements bewteen the in,out boound.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Generating random sample of given dimentions
**Note - Random numbers are generated between 0 to 1. Multiply them with an appropriate factor to get required outcome.**

In [30]:
np.random.random_sample((3, 2))

array([[0.18626021, 0.34556073],
       [0.39676747, 0.53881673],
       [0.41919451, 0.6852195 ]])

### Basic array operations
**Note - The operations are vectorised**


In [35]:
x = np.array([2,4,8,16])
y = np.array([1,1,0,1])

In [36]:
print(x + y) ## Operation peformed element by element.
print(x - y)
print(x * y)

[ 3  5  8 17]
[ 1  3  8 15]
[ 2  4  0 16]


In [39]:
z = np.array([[10,20,30,40],[100,200,300,400]])

print(z + y) ## When we are performing operation on two arrays,make sure that array are compatible and diemsnions are same.
print(z - y)
print(z * y)

[[ 11  21  30  41]
 [101 201 300 401]]
[[  9  19  30  39]
 [ 99 199 300 399]]
[[ 10  20   0  40]
 [100 200   0 400]]


### Matrix multiplication

In [46]:
s = np.array([[1,2,3],[2,3,4]])
t = np.array([[10,20,30,40],[100,200,300,400]])
print(s.shape)
print(s.T.shape)
print(t.shape)
print(np.matmul(s.T,t))

(2, 3)
(3, 2)
(2, 4)
[[ 210  420  630  840]
 [ 320  640  960 1280]
 [ 430  860 1290 1720]]


### Advanced array operations

In [47]:
a4 = np.random.random_sample(10) ## Create an array with 10 random values.
print(a4) ## Display an array.
print(np.min(a4)) ## Get minimum value from array.
print(np.max(a4)) ## Get maxumun value from array.
print(np.sum(a4)) ## Get sum of the all element of an array.
print(np.cumsum(a4)) ## Get cummilative sum of an array.
print(np.sqrt(a4)) ## Get square root values for each element of an array.
print(np.log(a4)) ## Get log for each eleement of an array.

[0.20445225 0.87811744 0.02738759 0.67046751 0.4173048  0.55868983
 0.14038694 0.19810149 0.80074457 0.96826158]
0.027387593197926163
0.9682615757193975
4.863913992386717
[0.20445225 1.08256969 1.10995728 1.78042479 2.19772959 2.75641942
 2.89680636 3.09490785 3.89565242 4.86391399]
[0.45216396 0.9370792  0.16549197 0.8188208  0.64599133 0.74745557
 0.37468245 0.44508593 0.89484332 0.98400283]
[-1.58742083 -0.12997494 -3.59766517 -0.39978003 -0.87393838 -0.58216083
 -1.96335282 -1.61897581 -0.22221327 -0.03225301]


### Logical operations

In [51]:
a=np.array([1,3,9])
b=np.array([[1,2,9],[5,8,7]])

print(a==b) ## Compare element by element.
print(b>4)

[[ True False  True]
 [False False False]]
[[False False  True]
 [ True  True  True]]


### Subset and slicing

In [3]:
c=np.array([[4,5,10],[5,10,15],[7,8,3],[4,6,9],[10,15,20]])

print(c[:,:]) ## Get all rows and columns data.
print(c.shape) ## Get dimension of an array.
print(c[0:2,1:3]) ## Get first 2 rows and second,third column.
print(c[:,2]) ## Get 2 column data.
print(c[:,:2]) ## Get first and second column data.

[[ 4  5 10]
 [ 5 10 15]
 [ 7  8  3]
 [ 4  6  9]
 [10 15 20]]
(5, 3)
[[ 5 10]
 [10 15]]
[10 15  3  9 20]
[[ 4  5]
 [ 5 10]
 [ 7  8]
 [ 4  6]
 [10 15]]


In [56]:
## Copy.
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

200


### Advantage of Numpy Arrays

In [2]:
import time
size_of_vec = 10000000

In [3]:
## Add two big vectors.
t1 = time.time()
X = range(size_of_vec)
Y = range(size_of_vec)
Z_list = []
for i in range(len(X)):
    Z_list.append(X[i] + Y[i])

time.time() - t1

9.383185148239136

In [6]:
t1 = time.time()
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)
Z_numpy = X + Y

time.time() - t1

0.1496882438659668

In [ ]:
## We can observe using numpy it took very less time to add two vectors.

In [64]:
sum(Z_list != Z_numpy) ## Check Z_list and Z_numpy containns same values or not....if it reurn 0 then both are having same data.

0

In [7]:
Z_list[:10] ## Display first 10 values of Z_list.

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
Z_numpy[:10] ## Display first 10 values of Z_numpy.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])